language: java

jdk:
  - openjdk8

dist: xenial

before_install:
  - pip install --user codecov

script:
  - ./gradle/buildViaTravis.sh build

after_success:
  - codecov

deploy:
  provider: script
  skip_cleanup: true
  script: ./gradlew jib -PdockerGroup=${CI_PROJECT_NAMESPACE} -Djib.to.auth.username=${CI_REGISTRY_USER} -Djib.to.auth.password=${CI_REGISTRY_PASSWORD} -Prelease.useLastTag=true
  on:
    tags: true
    all_branches: true

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
